### ISSUE TITLE
What is the output? is:question

### ISSUE THREAD

**Issue by ErlendFax** [darienmt/CarND-Semantic-Segmentation-P2#1]
@darienmt what comes out of the network when predicting? Is it a similar colored image as those in the data set, or a green overlay as the images in the readme file? Can't find any code for post processing. Thank you! :)

**Comment by darienmt** [comment]
Take a look at the helper.py method get_test_output line 101. There the FCNN is used for inference. 

```
im_softmax = sess.run(
            [tf.nn.softmax(logits)],
            {keep_prob: 1.0, image_pl: [image]})
im_softmax = im_softmax[0][:, 1].reshape(image_shape[0], image_shape[1])
segmentation = (im_softmax > 0.5).reshape(image_shape[0], image_shape[1], 1)
mask = np.dot(segmentation, np.array([[0, 255, 0, 127]]))
mask = scipy.misc.toimage(mask, mode="RGBA")
street_im = scipy.misc.toimage(image)
street_im.paste(mask, box=None, mask=mask)
```

This code is provided by Udacity.
